baseURL = 'https://osacom.netlify.app/'
title = 'The Open Source Analytics Community'
theme = 'hugo-bootstrap'

disableHugoGeneratorInject = true
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = 'series'
  author = "authors"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"

  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true

    [markup.goldmark.parser]
      autoHeadingID = true
      wrapStandAloneImageWithinParagraph = false

      [markup.goldmark.parser.attribute]
        block = true
        title = true

    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false


# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
[params]
  description = "Some tagline or small description text."
  images = ['images/logo-h.svg','images/site-feature-image.png']
  mainMenuLogo = "images/logo-h.svg"

  themeColor = "#fff"

  [params.options]
    bootStrapJs = true
    breadCrumb = true
    listCategoryFilter = true
    listTagFilter = true


[[menus.main]]
name = "About"
url = "about"
weight = 10

[[menus.main]]
name = "News"
url = "posts"
weight = 20

[[menus.main]]
name = "Sessions"
url = "sessions"
weight = 30

[[menus.main]]
name = "Authors"
url = "authors"
weight = 40

[[menus.main]]
name = "Contact"
url = "contact"
weight = 50


[[menus.social]]
  name = "GitHub"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='/images/feather/feather-sprite.svg#youtube'/></svg>"
  url = "https://youtube.com"
  weight = 10
  title = "Visit our YouTube channel"

[[menus.social]]
  name = "Twitter"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-twitter'><use href='/images/feather/feather-sprite.svg#twitter'/></svg>"
  url = "https://twitter.com/jfilipecarneiro/"
  weight = 20
  title = "Follow us on Twitter"
